---
title: "trends.Rmd"
author: "William L'Heudé"
date: "29 novembre 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Cheese is good.

```{r}
library(gtrendsR)
library(ggplot2)
library(tidyverse)

camembert.trend <- gtrends(c("camembert"), gprop = "web", time = "all")[[1]]
class(camembert.trend)
head(camembert.trend)
class(camembert.trend$date)

ggplot(data = camembert.trend) + geom_line(mapping = aes(x= date, y = hits))
?gtrends

camembert.trend <- camembert.trend %>% filter(date >= as.Date("2009-01-01"))
ggplot(data = camembert.trend) + 
  geom_line(mapping = aes(x= date, y = hits)) +
  geom_vline(xintercept = as.Date("2017-01-20"), color = "red") #trump inauguration
  
library(Quandl)
camembert.price <- Quandl("BCHARTS/BITSTAMPUSD")
camembert.price <- camembert.price %>% filter(Date %in% camembert.trend$date) %>% select(Date, Close) %>% rename(date = Date, price = Close) %>% mutate(price = price*100/max(price))

camembert <- left_join(x = camembert.trend, y= camembert.price, by = "date")
head(camembert)

ggplot(data = camembert) + 
  geom_line(mapping = aes(x= date, y = hits)) +
  geom_line(mapping = aes(x= date, y = price), color = "gray") + 
  geom_vline(xintercept = as.Date("2017-01-20"), color = "red")


```